version: '3'

networks:
  laravel:
  app-shared:
    driver: bridge

services:
  dock:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_dock
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
    - ../:/var/www/html:delegated
    networks:
    - laravel
    - app-shared

  pgsql:
      image: postgres:12.3
      container_name: pgsql_dock
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        SERVICE_TAGS: dev
        SERVICE_NAME: pgsql
      ports:
        - "${POSTGRES_PORT}:5432"
      volumes:
        - ./pgsql:/var/lib/pgsql
      networks:
        - laravel